# Dockerfile for Streamlit
FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl build-essential

COPY ./ui/requirements-ui.txt /app/ui/requirements-ui.txt
WORKDIR /app
RUN pip install --no-cache-dir -r ./ui/requirements-ui.txt

COPY ./ui /app/ui

CMD ["streamlit", "run", "ui/app.py", "--server.port", "8501"]
