# Dockerfile for FastAPI
FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl build-essential

RUN curl -O https://ollama.com/download/ollama-linux && \
    chmod +x ollama-linux && \
    mv ollama-linux /usr/local/bin/ollama && \
    ollama pull gemma2:2b

COPY ./api/requirements-api.txt /app/api/requirements-api.txt
WORKDIR /app
RUN pip install --no-cache-dir -r ./api/requirements-api.txt

COPY ./api /app/api

CMD ["uvicorn", "api.router:app", "--host", "0.0.0.0", "--port", "80"]
