services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:80"
    networks:
      - backend
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
